# Generated by Django 2.2 on 2019-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190314_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pesel',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
